# Язык программирования
![изображение.png]()

## Версии python

Существует две основные версии python: 2 и 3.

Версия 2 считается устаревшей, ее поддержка завершена в [2020](https://pythonclock.org/).
Однако, в реальных проектах иногда требуется поддерживать работу устаревшего кода.
Подобные ситуации в данном курсе не рассматриваются.
Об основных отличиях версий можно узнать, перейдя по [ссылке 1](https://www.geeksforgeeks.org/important-differences-between-python-2-x-and-python-3-x-with-examples/) или по [ссылке 2](https://pythonworld.ru/osnovy/python2-vs-python3-razlichiya-sintaksisa.html).

В рамках этого курса будет использоваться версия 3.

## Множество реализаций Python

CPython — эталонная реализация языка программирования Python. Она компилирует код Python в промежуточный байт-код, который затем интерпретируется виртуальной машиной. CPython написан на C.

Помимо CPython существует множество других реализаций и для других языков програмирования:

| Название | Язык программирорвания |
| --- |  --- |
| CPython | C |
| Jython | Java |
| IronPython | C# |
| Brython | JavaScript |
| RubyPython | Ruby |

## Кроссплатформенность

*   Linux
*   MAC
*   Window

## Литература для самостоятельного изучения

Доступно в электронной библиотечных системах «Электронная библиотека Респубилки карелия»  (https://elibrary.petrsu.ru) или в «Университетская библиотека онлайн» (http://biblioclub.ru):
1.	Смирнов Н. В. Анализ данных. Учебное пособие для студентов, обучающихся по направлениям подготовки 09.03.02 «Информационные системы и технологии», 09.03.04 «Программная инженерия» (уровень бакалавриата). Часть 1. Python / Н. В. Смирнов, И. В. Данилова, Г. Э. Рего ; М-во науки и высш. образования Рос. Федерации, Федер. гос. бюджет. образоват. учреждение высш. образования Петрозав. гос. ун-т. — Петрозаводск : Издательство ПетрГУ, 2023. — 52 с. — ISBN 978-5-8021-4139-7. — Текст : электронный. — URL: http://elibrary.petrsu.ru/books/65485 (дата обращения: 02.08.2024)
Северенс Ч. Введение в программирование на Python. / 2-е изд., испр. – Москва: Национальный Открытый Университет «ИНТУИТ», 2016. – 231 с.
2. Шелудько В. М. Язык программирования высокого уровня Python. Функции, структуры данных, дополнительные модули : учебное пособие / В. М. Шелудько Ростов-на-Дону; Таганрог: Издательство Южного федерального университета, 2017. – 107 с. // Университетская библиотека ONLINE / компания «Директ-Медиа». – Электрон. дан. – [Москва]. – 2020. – URL: // Университетская библиотека ONLINE / компания «Директ-Медиа». – Электрон. дан. – [Москва]. – 2020. – URL: http://biblioclub.ru/index.php?page=book_view_red&book_id=500060
3.	Шелудько В. М. Основы программирования на языке высокого уровня Python : учебное пособие / В. М. Шелудько. – Ростов-на-Дону; Таганрог: Южный федеральный университет, 2017. – 147 с. // Университетская библиотека ONLINE / компания «Директ-Медиа». – Электрон. дан. – [Москва]. – 2020. – URL: // Университетская библиотека ONLINE / компания «Директ-Медиа». – Электрон. дан. – [Москва]. – 2020. – URL: https://biblioclub.ru/index.php?page=book&id=500056


Дополнительные книги и ресурсы
- Лутц М. Изучаем Python, 4-е издание. СПб.: Символ-Плюс, 2011. – 1280 с.
- Mark Lutz. Learning Python, Fifth Edition. O’Reilly Media, 2013.
- Кеннет Ритц, Таня Шлюссер.  Автостопом по Python. – СПб.: Питер, 2017. – 336 с.
- [Документация языка Python](https://docs.python.org)
- [Интерактивный учебник Python](https://www.learnpython.org/)

## Импорт модулей

Большое количество функций реализовано в дополнительных модулях.
Множество модулей доступно сразу после установки Python, их нужно только импортировать.
Для того, чтобы импортировать модуль в текущую программу, необходимо написать
ключевое слово **import**, а далее указать *название модуля*.
Целиком это выглядит как: <br>
*import название модуля*

В качестве примера импортируем модуль math. Этот модуль содержит математические функции. <br>
В начале программы добавляем строку:

In [ ]:
import math  # Импортируем модуль math в нашу программу

Все, что записано в строке после символа *#*, интерпретатор игнорирует. Это называется комментарием. Комментарии нужны для того, чтобы понимать логику работы написанного кода. С комментариями код становится понятнее, а понятность кода - это один из важных критериев его качества.

Вызовем функцию извлечения квадратного корня из модуля math с аргументом 4, а результат ее выполнения выведем на экране с помощью функции print:

In [ ]:
print(math.sqrt(4))

В блоках выше мы успешно импортировали модуль и вызвали функцию квадратного корня из него.
Чтобы вызвать функцию, необходимо написать конструкцию следующего вида:<br>
*название_модуля.название_функции(аргументы_функции)*

**Задача 1.**

In [ ]:
'''
Для использования многострочного комментария применяются тройные одинарные кавычки, как здесь.

В качестве упражнения попробуйте вызвать функцию pow(x,y) из модуля math, которая позволяет возвести число x в степень y, при этом используйте x = 5, y = 4.
После нахождения ответа, выведите его на экран.
На экране должно отобразиться число 625.
Не забудьте написать комментарий о том, что именно делает функция.
'''
# Введите код ниже данной строки

# Введите код выше данной строки

[Посмотреть ответ на задачу 1](#exercise_1)

Можно при подключении модуля задать ему другое имя:

In [ ]:
import math as mathlib  # Теперь все функции модуля math нужно вызывать с помощью mathlib.название_метода()

<br>

**Задача 2.**
Попробуйте вызвать функцию pow с новым названием модуля и вывести результат работы функции на экран.

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 2](#exercise_2)

Можно импортировать одну функцию (класс, объект) из модуля:

In [ ]:
from math import sqrt  # Теперь вызов работает просто как sqrt(аргумент), попробуйте вызвать на следующей строке

## Арифметика

In [ ]:
a = 2  # Создается переменная a со значением 2
b = 9  # Создается переменная b со значением 9
# В python для инициализации объекта достаточно указать название объекта и присвоить ему значение с помощью знака =
print('a + b = ', a + b)  # Сложение
print('a - b =', a - b)  # Вычитание
print('a * b =', a * b)  # Умножение
print('a / b =', a / b)  # Деление
print('a ** b =', a ** b)  # Возведение в степень
print('b ** 0.5 =', b ** 0.5)  # Корень
print('a % b =', a % b)  # Остаток от деления
print('b // 2 =', b // 2)  # Целая часть от деления на 2

# Создайте переменную c и, в качестве упражнения, проделайте различные операции с a,b,c ниже.

a + b =  11
a - b = -7
a * b = 18
a / b = 0.2222222222222222
a ** b = 512
b ** 0.5 = 3.0
a % b = 2
b // 2 = 4

В python можно проводить операцию над переменной и сохранять результат операции в нее же:

In [ ]:
a = 1
a = a + 1
a

2

Можно сократить запись этой операции. В python для  операции инкремента (декремента) вместо `i++` (`i--`) используется: `i += 1` ( `i -= 1`)

In [ ]:
a += 1  # a увеличится на один. Вместо единицы может быть любое другое число.
print(a)
a *= 2  # a будет умножено на 2.
print(a)
a -= 1  # От a отнимется единица.
print(a)
a /= 3  # a будет поделено на 3.
print(a)

3
6
5
1.6666666666666667

<br>


**Задача 3**. В качестве упражнения создайте переменную d, присвойте ей значение 5.<br>
Затем отнимите от d число 7 вышеуказанным способом.<br>
Затем умножьте d на число 10 вышеуказанным способом.<br>
Затем выведите d на экран. Должно получиться число -20.

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 3](#exercise_3)

## Форматиорване кода
С помощью отступов в **Python** регулируется принадлежность блока кода циклам, функциям, классам, условиям и т.д.
Строки кода, которые относятся к одному и тому же элементу программы, должны быть на одном уровне отступа.

1. В качестве отступа можно использовать 2 или 4 пробелла или *Tab* (не рекомендуется). При этом следует придерживаться одного формата во всей программе.
2. Длинные инструкции можно распологать на нескольких строках используя символ продолжения строки:

In [ ]:
import math
a = math.sqrt(9) + \
    math.pow(9, 2)
a

3. Если была открыта скорбка (, {, [ или тройные кавычки """, то строка будет продолжаться, пока не появится соответсвующий закрывающий символ.

In [ ]:
a = [1,
    2,

    3]

b = """a

b
c"""
print(a, b, sep='\n')  # sep - это разделитель. В данном случае печать каждого аргумента будет отделена переносом строки

Алгоритм выполнения программы, как правило, определяется выполнением различных условий. Если условие выполняется, то выполняется один блок кода, а если не выполняется, то другой.
Для реализации этого механизма в **python** есть условный оператор.

## Сравнение объектов. Условный оператор if
| Оператор | Значение |
| --- | --- |
| < | строго меньшне чем |
| <= | меньше или равно |
| > | строго больше |
| >= | больше или равно |
| == | равно |
| != | не равно |
| is | сравнение объектов |
| is not | отрицание сравнения объектов |

Запись условного оператора начинается с ключевого слова **if**, псоле которого указывается условие. Результат проверки условия возвращает значение типа **boolean**.
**Boolean** - это тип данных, который может принимать 2 значения: **True (1)** или **False (0)**.
Если результат проверки **True**, то выполняется код, который находится под блоком **if**.

Оператор **not** опровергает логическое после него. `not True` -> `False`, `not False` -> `True`.

На случай, если результат проверки условия if вернет False, то можно либо завершить работу условоного оператора, либо написать
другое условие с помощью ключевого слова elif, либо написать блок else.

Пример оператора if:

In [1]:
a = 5  # Инициализируется переменная
if a > 0:
    print('a - положительное')  # Эта строка выполнится, если проверка условия вернет результат True
elif a == 0:  # Эта строка выполнится, если проверка первого условия вернет результат False
    print('a - равно 0')
else:  # Эта строка выполнится только в случае, если проверки первых двух условий вернут результат False
    print('a - отрицательное')

a - положительное

Обратите внимание, что для проверки условия используется оператор **==** (двойное равно), а для присвоения используется **=** (одинарное равно).
С точки зрения **Python** - это два разных оператора. Одна из частых ошибок - написание оператора сравнения с одинарным равно.
Также в условном операторе используются отступы (например, 4 пробела), которые позволяют отделить набор строк кода, которые выполняются при выполнении условия, о них будет сказано ниже.

В **python** переменные принимают **True** и **False** значения в условных операторах, так что можно, и рекомендуется, не использовать явно операторы сравнения.
### Плохой код:

In [ ]:
a = True  # Присваиваем переменной a значение True. Тип данных Boolean.
if a == True:  # "Плоходй код", т.к. такая строчка приведет к сравнению True == True
    print('a is True')

### Хороший код:

In [ ]:
a = True
if a:  #  "Хороший код"
    print('a is True')
if not a:
    print('a is not True')

Таким способом можно проверять переменные, имеющие **True** или **False** значения:

In [ ]:
a = ''  # a - пустая строка
if a:
    print(a)
if not a:  # Здесь результат проверки будет обратным результату проверки a. Если "a" - True, то "not a" вернет False и наоборот.
    print('a is empty')

b = 0
if b:
    print('b is True')
if not b:
    print('b is False')

c = 1
if c:
    print('c is True')
if not c:
    print('c is False')

**is** и **==** - это не одно и то же. Оператор **==** проверяет на равенство значений объектов, а **is** проверяет на совпадение объектов (пояснение в блоке немного ниже).

Объект, имеющий "непустое значение", т.е. неравный None, 0, '' (пустая строка), соответсвует логическому значению Истина (**True**).

Если необходимо именно значение **True**:

In [ ]:
a = 1
print('a =', a)
if a == True:
    print('a == True')
else:
    print('a != True')

# В данном случае is проверяет не значение "a", а ее ссылку на объект True.
if a is True:
    print('a is True')
else:
    print('a is not True')

Тип данных None означает отсуствие значения. Это не то же самое, что 0 или пустая строка.
0 или пустая строка могут нести какой-то смысл (например, температура 0 градусов).
В то же время None означает отсутствие значения как такового.
Проверка на значение None:

In [ ]:
a = None
if a is None:
    print('a is None')

Условные операторы можно писать в одну строку в тех случаях, когда подразумеваются короткие конструкции, которые
можно описать лаконично.
Сначала пишется то, что выполнится в случае **True**, затем ключевое слово **if** и условие, затем ключевое слово **else** и код, который выполнится в случае **False**.
Пример *однострочного* **if**:

In [ ]:
a = 1 if True else 2
print(a)

`==` - проверяет равенство значений объектов

`is` - проверяет идентичность объектов

`id(obj)` - функция, возвращает идентификатор объекта. Идентификатор присваивается объекту при его создании. Идентификатор является адресом объекта в оперативной памяти и будет отличаться при каждом запуске программы.

In [ ]:
a = 1
b = 1
c = 1.0
print(id(a))
print(id(b))
print(id(c))

if a == c: print('Значения a и c совпадают')
if not a is c: print('Но a и c - это разные объекты, их типы не совпадают')

В случае отстуствия необходимости выполнения действий, в том числе, и в условных операторах используется специальное слово `pass`.

In [9]:
a = 2
if a == 2:
    pass
else:
    print('NO!')

Если не указать `pass`, то последует ошибка:

In [ ]:
if a == 2:

else:
    print('NO!')

In [ ]:
# Эту конструкцию можно описать и по-другому, с помощью оператора != (не равно).
a = 3
if a!=2:
    print('NO!')

<br>

**Задача 4**. В качестве упражнения предлагается инициализировать переменную *b* и присвоить ей значение 5.<br>
Далее необходимо реализовать последовательную проверку нескольких условий (с помощью операторов **if** и **elif**).<br>
Множества значений переменной, при которых достигается истина в том или ином условии, не должны пересекаться между собой. <br>
При успешном прохождении какой-либо из проверок, необходимо вывести на экран текст, который соответствует логике данной проверки. <br>
Измените значение *b* так, чтобы другое условие было выполнено. <br>
Запустите код несколько раз с разными значениями b. <br>
'''<br>
Псевдокод решения задачи.<br>
b = 5 <br>
Если: b<0 <br>
То: Вывести текст: b - отрицательное число. <br>
Иначе: Если b = 0 <br>
То: Вывести текст: b равно нулю.
Иначе: Вывести текст: b - положительное число.<br>
Конец.<br>
'''

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 4](#exercise_8)

## Циклы: всего 2 типа
Цикл - это блок кода, содержимое которого (тело цикла) может выполняться больше одного раза.
#### Цикл **while**
Цикл **while** выполняется до тех пор, пока выполняется заданое условие.
В начале каждой итерации проверяется выполнение условия. Если проверка возвращает **истину** (**True**), то выполняется тело цикла.
Если проверка возвращает **ложь** (**False**), то выполняется блок кода **else**.
Теоретически цикл **while** может быть бесконечным, однако крайне не рекомендуем писать подобный код (за исключением отдельных случаев, например, построения сокета).
Цикл **for** выполняется для заданного количества элементов из набора (списка, множества, ...).

Ключевое слово **continue** прерывает текущую итерацию цикла и переходит на следующую.
Ключевое слово **break** прерывает выполнение кода в цикле и выводит из него. Оператор **else** в таком случае не выполняется, т.е. **else** работает так же, как и в условном операторе.
Проверьте, как и когда выполняются условия **continue**, **break**, **else**:

In [ ]:
a = 0
while a < 5:
    a += 1
    print(a)
    if a == 2:  # Пропустить ход если а == 2
        continue
    if a == 4:  # Выйти из цикла если a == 4
        break
    print('continue ', a)
else:
    print('all out')  # Строка не выполнится, так как при a=4, выполнится break и else будет пропущен

<br>

**Задача 5**. В качестве упражнения измените код в предыдущей ячейке таким образом, чтобы блок else выполнился.<br>

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 5](#exercise_10)<br>

Рассмотрим один тип данных: **список** - набор значений. Пример списка из двух значений и применения функции `len()`, которая возвращает количество элементов в нем:

In [ ]:
a = [1, 2]
print(a)
print('len(a) = ', len(a))

[1, 2]
len(a) =  2

#### Цикл **for** :

In [ ]:
for i in [1, 2, 3]:  # Для каждого элемента из списка элементов [1, 2, 3] выполнится своя итерация. В данном случае все элементы выведутся на экран.
    print(i)

Функция **range** позволяет генерировать ряды чисел.
В случае, когда указан один аргумент, генерируется ряд чисел от 0 до указанного аргумента, **не включая сам аргумент**.

In [ ]:
for i in range(10):  # Цикл от 0 до 9
    print("Вывожу число: " + str(i))
print("Конец первого цикла")

В случае, когда функции **range** передаются два аргумента, аргументы означают начало диапазона чисел (включительно) и конец диапазона (не включительно)

In [ ]:
# Данный цикл отработает в диапазоне от 5 до 9
for i in range(5, 10):
    print("Вывожу число: " + str(i))
print("Конец второго цикла")

В случае, когда функции **range** передаются три аргумента, аргументы означают начало диапазона чисел (включительно), конец диапазона (не включительно) и шаг увеличения (уменьшения) чисел в последовательности.

In [ ]:
# Данный цикл отработает в диапазоне от 5 до 15 с шагом 3
for i in range(5, 15, 3):
    print("Вывожу число: " + str(i))
print("Конец третьего цикла")

<br>

**Задача 6**. В качестве упражнения напишите цикл for, который выведет значения от 100 (включительно) до 0 (не включительно), кратные 10.

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 6](#exercise_9)

---

<br>

**Задача 7**. В качестве упражнения напишите цикл while, который выведет значения от 100 (включительно) до 0 (не включительно), кратные 10.

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 7](#exercise_11)

## Пример: отфильтровать все элементы со значением больше 2.

Способ 1. Стандартный цикл:

In [ ]:
a = [1, 2, 3, 4]
b = []
for i in a:
    if i > 2:
        b.append(i) # Метод append() добавляет новый элемент в список
print(b)

Способ 2. Списковое включение.

В примере ниже создается список из значений списка a, которые больше 2:

In [ ]:
a = [1, 2, 3, 4]
b = [i for i in a if i > 2]  # Циклы также будут рассмотрены позднее
print(b)

Функция `filter()` подробнее рассматривается в следующих блокнотах, к способу 3 можно вернуться после этого или изучить эту тему самостоятельно.

Способ 3. Использование функции `filter()`:

In [ ]:
a = [1, 2, 3, 4]
b = list(filter(lambda x: x > 2, a))  # lambda функции рассматриваются позднее
print(b)

## Пример. Увеличить значение каждого элемента на 3.

Способ 1. Стандартный цикл:

In [ ]:
a = [1, 2, 3]
for i in range(len(a)):
    a[i] += 3
print(a)

Способ 2. Списковое включение:

In [ ]:
a = [1, 2, 3]
a = [i + 3 for i in a]
print(a)

Функция `map()` подробнее рассматривается в следующих ноутбуках, к способу 3 можно вернуться после этого или изучить эту тему самостоятельно.

Способ 3. Использование функции `map()`:

In [ ]:
a = [1, 2, 3]
a = list(map(lambda x: x + 3, a))
print(a)

## Типы данных
Основные типы данных указаны в таблице.

|Тип объекта | Object type | Примеры объектов/литералов |
|---|---|---|
|Числа| Numbers | `1234, 3.1415, 3+4j, 0b111, Decimal(), Fraction()` |
|Строки| Strings | `'spam', "Bob's", b'a\x01c', u'sp\xc4m'` |
|Списки| Lists | `[1, [2, 'three'], 4.5], list(range(10))` |
|Словари| Dictionaries | `{'food': 'spam', 'taste': 'yum'}, dict(hours=10)` |
|Кортежи| Tuples | `(1, 'spam', 4, 'U'), tuple('spam'), namedtuple` |
|Файлы| Files | `open('eggs.txt'), open(r'C:\ham.bin', 'wb')` |
|Множества| Sets | `set('abc'), {'a', 'b', 'c'}` |
|Другие ключевые типы| Other core types | Booleans, types, None |
|Объекты программ| Program unit types | Functions, modules, classes |
|Типы, связанные с выполнением программы| Implementation-related types | Compiled code, stack tracebacks |

In [ ]:
# Int - тип данных, который соответствует целым числам
a = 123
type(a)

int

### Строки

Тип string является строковым типом данных.
Одинарные и двойные кавычки определяют однострочные строки, при этом экранируя двойные и одинарные кавычки внутри соответсвенно. Это позволяет использовать соответствующие символы для собственных нужд.

Для создания многострочных строк используются три кавычки подряд.

In [ ]:
s = "Hello, world!"
print(type(s))  # Тип String
print('Hello, world!')  # Обычная строка, обернутая в одинарные кавычки
print("Hello, world!")  # Обычная строка, обернутая в двойные кавычки
print('"Hello, "World"!')  # Строка, обернутая в одинарные кавычки (двойные кавычки тоже обернуты)
print("'Hello, 'World'!")  # Строка, обернутая в двойные кавычки (одинарные кавычки тоже обернуты)
print("""Hello "everybody" in the

'World'!""")  # Многострочная строка. Внутри присутствуют как одинарные, так и двойный кавычки.

Можно делать срезы строк, а также складывать их.

In [ ]:
a = 'Hello world!'
print(a[2:7])  # Выведутся только указанные символы (последний не включительно)

In [ ]:
a = 'hello' + ' ' + 'world'
print(a)

<br>

**Задача 8**. В качестве упражнения напишите код, который выводит слово wonderful из переменной a

In [ ]:
# Напишите свой код в данной ячейке
a = "What a wonderful world!"

[Посмотреть ответ на задачу 8](#exercise_4)

#### Методы строк
`s` - строка

| Метод | Описание |
| --- | --- |
| `s.count(sub [,start [,end]])` | Посчитывает число вхождений заданной подстроки sub |
| `s.endswith(suffix [,start [,end]])` | Проверяет оканчивается ли строка подстрокой suffix |
| `s.find(sub [,start [,end]])` | Отыскивает первое вхождение подстроки sub или возвращает -1 |
| `s.index(sub [,start [,end]])` | Отыскивает первое вхождение подстроки sub или возвращает исключение |
| `s.isalnum()` | Проверяет, являются ли все символы в строке алфавитно-цифровыми |
| `s.isalpha()` | Проверяет, являются ли все символы в строке алфавитными |
| `s.isdigit()` | Проверяет, являются ли все символы в строке цифрами |
| `s.islower()` | Проверяет, являются ли все символы в строке символами нижнего регистра |
| `s.isspace()` | Проверяет, являются ли все символы в строке пробельными символами |
| `s.lower()` | Преобразует все символы в нижний регистр |
| `s.lstrip([chrs])` | Удаляет все пробельные символы из начала строки или символы, перечисленные в chrs |
| `s.partition(sep)` | Разбивает строку по подстроке разделителю |
| `s.replace(old, new [,maxreplace])` | Замещает подстроку old строкой new |
| `s.rfind(sub [,start [,end]])` | Отыскивает последнее вхождение sub |
| `s.rindex(sub [,start [,end]])` | Отыскивает последнее вхождени sub или возбуждает исключение |
| `s.rjust(width)` | Выравнивает строку s по правому краю в поле шириной width |
| `s.rpartition(sep)` | Разбивает строку по подстроке sep, но начинает поиск с конца строки  |
| `s.rsplit([sep])` | Разбивает строку по подстроке sep на множество разбиений, начинает поиск с конца строки |
| `s.split([sep [, maxsplit])` | Разбивает строку по подстроке разделителю sep на множество разбиений |
| `s.splitlines()` | Разбивает строку в список строк |

### Форматирование вывода
Обратите внимание, при именовании объектов в Python используется нотация snake_case (слова начинаются с маленькой буквы и соединены подчеркиванием), а не CamelCase (слова пишутся сбольшой буквы без подчеркиваний).

In [ ]:
first_name = 'Vasya'
age = 19

#### Способ 1
Склеивание множества переменных в 1 строку

In [ ]:
print(first_name, 'is', age, 'years old')  # Порядок элементов важен!

#### Способ 2
Подставление значений переменных в строку из указаных после. Требуется соответствие типов.

In [ ]:
print('%s is %d years old' % (first_name, age))

Различные типы: https://pythonworld.ru/osnovy/formatirovanie-strok-operator.html

|Формат |Что получится|
| --- | --- |
|'%d', '%i', '%u' |Целое число|
|'%f', '%F' |Вечественое число (с плавающей точкой)|
|'%s' |Строковая переменная
|'%o' |Число в восьмеричной системе счисления|
|'%x' |Число в шестнадцатеричной системе счисления (буквы в нижнем регистре)|
|'%X' |Число в шестнадцатеричной системе счисления (буквы в верхнем регистре)|
|'%e' |Число с плавающей точкой с экспонентой (экспонента в нижнем регистре)|
|'%E' |Число с плавающей точкой с экспонентой (экспонента в верхнем регистре)|
|'%g' |Число с плавающей точкой, с экспонентой (экспонента в нижнем регистре), если она меньше, чем -4 или точности, иначе обычный формат|
|'%G' |Число с плавающей точкой, с экспонентой (экспонента в верхнем регистре), если она меньше, чем -4 или точности, иначе обычный формат|
|'%c' |Символ (строка из одного символа или число - код символа)|
|'%r' |Строка (литерал python)|
|'%%' |Знак '%'|

<br>

**Задача 9**. В качестве упражнения напишите код, который реализует строку следующего содержания: "Ivanov Vasya has the cat Barsik". <br>
При выполнении воспользуйтесь переменными first_name, second_name, cat_name.

In [ ]:
# Напишите свой код в данной ячейке
second_name = 'Ivanov'
cat_name = 'Barsik'

[Посмотреть ответ на задачу 9](#exercise_5)

Вставка значений переменных в строку вывода, как указано в таблице выше:
* %s - строковая переменная
* %i - целое число
* %f - вещественное число
* .2f - вещественное число с округлением до двух знаков полсе запятой

In [ ]:
print('Cost of %s is %i' % ('banana', 123))

print('Cost of %s is %f' % ('banana', 123.567))

# Сократим количество выводимых символов дробной части
print('Cost of %s is %.2f' % ('banana', 123.56789))

#### Способ 3
Подстановка, используя функцию *format*:

In [ ]:
print('{} is {} years old'.format(first_name, age))  # Вместо {} подставится first_name и age соответственно
print('{name} is {age} years old'.format(name=first_name, age=age))

#### Способ 4
Подставление переменных прямо в строку. Обратите внимание на символ `f`, стоящий перед строкой. Он означает, что данная строка является форматируемой, и в ней нужно подставить значения переменных, стоящих в фигурных скобках {}.
Этот метод работает только в python, начианя с версии 3.6.

In [ ]:
print(f'{first_name} is {age} years old')

### Списки

#### Концепция списков
Тип данных List является списком. Списки - это набор объектов с упорядоченными индексами.

In [ ]:
# Объявление списков
a = []
a = list()
a

In [ ]:
os = ['gnu/linux', 'macos', 'freebsd']
os

К **спискам** можно обращаться поэлементно, а можно обращаться ко всему **списку** сразу.

In [ ]:
my_list = [1, "Hello, world!", [3,4,5]]
print("Список целиком:", my_list)
print("Список целиком поэлементно:")
print(*my_list)
print("Первый элемент списка:" + str(my_list[0]))

В качестве элементов списка могут быть объекты различной природы: числа, строки, другие списки и так далее.

In [ ]:
a = [1, "Dave", 3.14, ['Mark', 7, 9, [100, 101]],10]
print(a[1])  # Dave
print(a[3][2])  # 9
print(a[3][3][1])  # 101

#### Конкатенация (объединение) списков:

In [ ]:
a = [1, 2, 3] + [4, 5]
print(a)

#### Срезы списков:

In [ ]:
a = [1, 2, 3, 4, 5]
print('Первые два элемента:', a[:2])
print('После первых двух элементов:', a[2:])
print('Между вторым и четвертым элементами:', a[2:4])
print('Последний элемент:', a[-1])

#### Методы списков
| Метод | Описание |
| --- | --- |
| `list(s)` | Преобразует объект s в список |
| `s.append(x)` | Добавляет новый элемент x к списку s |
| `s.extend(x)` | Добавляет новый список x в конец списка s |
| `s.count(x)` | Определяет количество вхождений x в списке s |
| `s.index(x [, start [, stop]])` | Находит индекс элемента со значением x |
| `s.insert(i, x)` | Вставляет x после элемента с индексом i |
| `s.pop([i])` | Возвращает i-й элемент, удаляет его из списка. Если i не указан - берется последний |
| `s.remove(x)` | Находит и удаляет элемент со значением x |
| `s.reverse()` | Изменяет порядок следования элементов на обратный |
| `s.sort([key [, reverse]])` | Сортирует элементы списка s |

In [ ]:
a = 'Hello world'
s = list(a)  # Преобразуем строку в список
print(s)
print(type(s))  # Убедимся, что тип действительно "список"

#### Индексация элементов

**Первый способ**: функция `enumerate` для получения позиции элемента в списке и самого элемента.

In [ ]:
a = ['a', 'b', 'c']
for i, a in enumerate(a):
    print('Под номером {} в списке находтся элемент {}'.format(i, a))

**Второй способ**: функции *range* и *len*

In [ ]:
a = ['a', 'b', 'c']
for i in range(len(a)):
    print('Под номером {} в списке находтся элемент {}'.format(i, a[i]))

<br>

**Задача 10**. В качестве упраженения создайте список из 3-х элементов и выведите на экран второй элемент списка. Помните, что нумерация начинается с нуля.

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 10](#exercise_6)

### Копия и псевдокопия

In [ ]:
a = [1, 2, 3]
b = a  # Псевдокопия. Переменные a и b являются указателями на один и тот же объект [1, 2, 3] в оперативной памяти
print('a:', a)

print('Изменим один из элементов b, изменится ли a?')
b[1] = 100
print('a:', a)
print('b и a указывают на один объект? Ответ:', b is a)  # Ключевое слово is будет объяснено позже

In [ ]:
a = [1, 2, 3]

b = a.copy()  # Копия
print('b =', b, ' - полная копия a')
print('b - это a? Ответ:', b is a, '\n')

b = a[:]
print('b =', b, ' - полная копия a')
print('b - это a? Ответ:', b is a, '\n')

print('Изменим один из элементов b, изменится ли a?')
b[1] = 7
print('b =', b)
print('a =', a)

<br>

**Задача 11**. В качестве упражнения создайте список, затем его копию, измените какой-либо элемент в копии, затем выведите на экран оба списка. <br>
Убедитесь, что списки различаются на один элемент

In [ ]:
# Напишите свой код в данной ячейке

[Посмотреть ответ на задачу 11](#exercise_7)

### Словарь

Ассоциативный массив, содержащий объекты, индексированные неупорядоченными ключам.

Пустой список:

In [ ]:
d = {}
d = dict()

В списках применяется последовательная индексация элементов (0,1,2...). Словари (Dictionaries) по своей природе похожи на списки, но индексация элементов в них происходит по ключу. Словари - это набор объектов c неупорядоченными индексами.
Отличить словарь от списка можно также по фигурным скобкам, которые используются при инициализации словаря

In [ ]:
my_dict = {"first": "Ivanov", "second": "Petrov"}
print(my_dict["first"])  # Обращение к значению по ключу "first" в словаре my_dict
print(my_dict)  # Вывод словаря целиком

Получение значения в словаре по ключу:

In [ ]:
d = {'name': 'Vasya',
     'age': 18}
print(d)
print(d['name'])

Изменение значения в словаре по ключу:

In [ ]:
d = dict(name='Vasya', age=18)
print(d)
d['age'] = 19
print(d)

In [ ]:
d = {'a': 1, 'b': 2}
print('Список значений в словаре:', d.values())
print('Список ключей в словаре:', d.keys())
print('Список пар занчений (ключ, значение) в словаре:', d.items())

###### get(key [, defval])
Если ключ `key` присутствует в словаре, то метод возвращает значение, соответствующее этому ключу. Если ключ отсутствует, то возвращается значение `None` или значение из второго параметра `defval` (дефолтное значение)

In [ ]:
d = {'a': 1, 'b': 2}
print(d.get('a'))
print(d.get('c'))

###### setdefault(key [,defval])
Если ключ присутствует в словаре, то метод возвращает значение, соответствующее этому ключу. Если ключ отсутствует, то вставляется новый элемент со значением, указанным во втором параметре. Если второй параметр не указан, то `None`:

In [ ]:
d = {'a': 1, 'b': 2}
print(d.setdefault('a'))

d.setdefault('d', 3)
print(d)

###### pop
удаляет элемент с указанным ключом и возвращает его значение. Если ключ отсутствует, то возвращается значение из второго параметра. Если ключ отсутствует и второй параметр не указан, то возбуждается исключение KeyError.

In [ ]:
d = {'a': 1, 'b': 2}
d.pop('a')

In [ ]:
d = {'a': 1, 'b': 2}
d.pop('e', 0)  # Попытка достать значение, которого нет в словаре, но с указанием запасного параметра

Метод `clear()` удаляет содержимое словаря

In [ ]:
d = {'a': 1, 'b': 2}
d.clear()
print('Теперь d =',d)

`dict.update([other])` - обновляет словарь, добавляя пары (ключ, значение) из other. Существующие ключи перезаписываются:

In [ ]:
d = {'a': 1, 'b': 2}
d.update({'c': 3})
print(d)

In [ ]:
my_dict = {'key': 'value'}
my_dict.update({'another_key': 'another_value'})  # Дополняем
print(my_dict)
my_dict.update({'another_key':'yet_another_value'})  # Обновляем
print(my_dict)

К словарю так же применимы стандартные функции для вычисления длинны, копирования, копирования с вложениями:

dict. `len()` — возвращает число пар

dict. `copy()` — создает псевдокопию словаря

dict. `deepcopy()` — создает полную копию словаря

`in` — оператор, проверяет наличие значения по ключу

In [ ]:
d = {'a': 1, 'b': 2}
print('a' in d)  # Проверка есть ли a в d

###### del
удаление из словаря по ключу

In [ ]:
d = {'a': 1, 'b': 2}
del d['a']
print(d)

На самом деле у `del` куда большие применений чем просто очистка словарей. Это спецальное слово для удаления любых объектов. Пример вызовет ошибку, т.к. в нем происходит обращение к уже удаленному элементу:

In [ ]:
a = 123
del a  # Удаление переменной
print(a)  # NameError: name 'a' is not defined  -- так как она была удалена

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
del a[3:6]  # Можно удалить часть списка. После этого индексация последующих элементов изменяется
print(a)

#### Упражнение
В качестве упражнения создайте словарь и потренируйтесь в применении основных функций, описанных выше.

In [ ]:
# Напишите свой код в данной ячейке

###  Кортежи
Кортежи(Tuples) - это неизменяемые объекты. Их *неизменяемость* означает, что мы не можем переопределить отдельный элемент кортежей.

In [ ]:
# В списках и словарях изменения возможны.
my_list[0] = "New element!"
print(*my_list)
my_dict["first"] = "Egorova"
print(my_dict)

In [ ]:
# Инициализация кортежа
a = ()
# или
a = tuple()
print('a =', a)

In [ ]:
a = (1, 2, 'Hello')
print('a =', a)

In [ ]:
a = 1, 2, 'World!'
print('a =', a)

In [ ]:
a = (1, )
print('a =', a)

In [ ]:
print("Создаем кортеж из одного элемента: a = ('s').")
a = ('s')
print("А получаем строку ", a)  # 's'

print("Создаем кортеж из одного элемента таким образом: a = ('s',).")
a = ('s', )
print("Получаем кортеж ", a)  # ('s',) – это уже кортеж!

In [ ]:
# Для инициализации кортежа применяются круглые скобки
my_tuple = (1,2,3,4,5, "Вышел зайчик погулять!")
print(my_tuple)

Код ниже приведет к ошибке, так как кортеж неизменяем:

In [ ]:
my_tuple[5] = "Вышел заяц на крыльцо"  # TypeError: 'tuple' object does not support item assignment

TypeError: ignored

#### Плюсы кортежей:
+ Защищены от изменений
+ Меньший размер
+ Возможность использовать кортежи в качестве ключей словаря

In [ ]:
a = (1, 2, 3)
b = [1, 2, 3]
print('размер кортежа в байтах: ', a.__sizeof__())
print('размер списка в байтах: ', b.__sizeof__())

### Файлы

Тип данных файлы позволяет работать с файлами. Подробнее об этом будет рассказано в следующих блокнотах.

### Множества
Для хранения неупорядоченных коллекций объектов. Объекты во множестве не поторяются.

In [ ]:
s = set()  # Изменяемое множество
f = frozenset()  # Неизменяемое множество

In [ ]:
set([1, 2, 3, 4])

Тип файлов множества (sets) содержит неупорядоченные неповторяющиеся элементы в случайном порядке. Например, слово "hello" содержит две буквы l, а во множество войдет только одна:

In [ ]:
set('hello')

In [ ]:
s = set([1, 2, 3])
s.add(1)  # Элемент не добавится, так как уже имеется во множестве
s.add(4)  # Элемент добавится, так как его нет во множестве
print(s)

| Операция | Описание |
| --- | --- |
|`a \| b`|Объединение|
|`a & b`|Пересечение|
|`a - b`|Разность|
|`a ^ b`|Симметричная разность|

Два списка не могут содержаться в множестве:

In [ ]:
a = [1, 2, 3]
b = set(a)
print(b)

In [ ]:
a = [1, 2, 3]
c = [4, 5, 6]
b = set(a, b)  # TypeError: set expected at most 1 arguments, got 2

#### Методы множеств:

| Метод | Описание |
| --- | --- |
| len(s) | Возвращает количество элементов во множестве s |
| s.copy() | Создает копию множества s |
| s.difference(t) | Разность множеств. Возвращает элементы из s, отсутсвующие в t |
| s.intersection(t) | Пересечение множеств. Возвращает элементы из s и t |
| s.isdisjoint(t) | Возвращает True, если s и t не имеют общих элементов |
| s.issubset(t) | Возвращает True, если s является подмножеством t |
| s.issuperset(t) | Возвращает True, если s является надмножеством t |
| s.symmetric_difference(t) | Симметричная разность. Возвращает элементы из s и t, но не те которые есть одновременно в s и т |
| s.union(t) | Обхединение множеств. Возвращает все элементы из s и t |
| s.add(item) | Добавляет элемент item в s. Если он уже есть, то ничего не делает. |
| s.clear() | Удаляет все элементы множества s |
| s.difference_update(t) | Удаляет все элементы из s, которые есть в t |
| s.discard(item) | Удаляет item из s. Ничего не делает, если этот элемент отсутсвует во множестве |
| s.intersection_update(t) | Находит пересечение s и t, результат остовляет в s |
| s.pop() | Возвращает произвольные элемент из множества и удаляет его из s |
| s.remove(item) | Удаляет item из s. Если его нет во множестве, то возбуждается исключение KeyError |
| s.symmetric_difference_update(t) | Находит симметричную разность s и t и оставляет результат в s |
| s.update(t) | Добавляет все элементы из t в s. |

<br>

**Задача 12**. Инициализируйте 2 множества, которые отличаются на 2 элемента.<br>
Затем, используя функцию **intersection_update**, удалите из множеств элементы, которые не входят в оба множества. <br>
Убедитесь, что множества содержат одинаковые элементы с помощью функции **intersection**.

In [ ]:
# Напишите свой код в эту ячейку

[Посмотреть ответ на задачу 12](#exercise_12)

### Преобразование типов данных

| Функция | Описание |
| --- | --- |
| `int(x [,base])` | Преобразовывает х в целое число. Например, int(12.4) -> 12 |
| `long(x [,base] )` | Преобразовывает х в long. Например, long(20) -> 20L |
| `float(x)` | Преобразовывает х в число с плавающей точкой. Например float(10) -> 10.0 |
| `complex(real [,imag])` | Создает комплексное число. Например complex(20) -> (20+0j) |
| `str(x)` | Преобразовывает х в строку. Например str(10) -> '10' |
| `tuple(s)` | Преобразовывает s в кортеж. Например tuple("hello") -> ( "h","e","l","l","o" ) |
| `list(s)` | Преобразовывает s в список. Например list("Python") -> [ "P","y","t","h","o","n" ] |
| `dict(d)` | Создает словарь из d. Например dict( [ (1,2), (3,4) ] ) -> { 1:2, 3:4 } |

In [ ]:
int('12', base=11)
# base - основание системы счисления. Число 12 в заданной системе счисления преборазуется в число 13 в 10-й системе счисления, т.к. 12 -> 1*11**1 + 2*1**0 = 13

In [ ]:
# Типы данных можно преобразовывать. Например:
a = 2123
print(type(a))  # Сейчас a - целое число, поэтому тип int.
a = str(a)  # Преобразуем a к типу string.
print(type(a))  # Сейчас a - строка, поэтому тип str.
a = int(a)  # Преобразуем a к типу int.
type(a)  # Сейчас a - снова целое число, поэтому тип int.

**Важно!** Не все типы данных можно преобразовывать между собой. Существует также множество других типов данных, в том числе пользовательских (которые определяет сам программист). Остальные типы данных будут освещены в следующих ,,блокнотах.

Подробнее о преобразовании типов данных можно прочитать [тут](https://myrobot.ru/python/02_type_conversion.php).

## underscore

**`_` (подчеркивание, underscore)** - специальная переменная в **python**. Она используется для сохранения результата последней выполненой команды и, в том числе, для обозначения переменных, которые не будут использоваться:

In [ ]:
for _ in range(5):
    print("I can use underscore")

Забегая сильно вперед, немного коснемся темы объектно-ориентированного программирования. При именовании переменных двойной underscore обычно используют для обозначения функций и переменных, которые будут использоватся только внутри класса.

In [ ]:
class A():  # Инициализируем класс A
    def __init__(self):  # Инициализируем конструктор класса, который вызывается при инициализации экземпляра класса
        self._var = 'su'
        self.__var = 'du'

a = A()  # Инициализируется экземпляр класса А
print('a._var = ', a._var)

Двойной **underscore** (`__`) во время создания класса транслируется в `_ИмяКласса__ИмяПеременной`:

In [ ]:
try:  # Это механизм исключений. Он будет объяснен позже
    a.__var  # AttributeError: 'A' object has no attribute '__var'
except AttributeError:
    print('no such attribute as __var')

print(a._A__var)

Более подробно данный механизм будет раскрыт в уроках про объектно-ориентированное программирование.

## Исключения

Некоторые участки кода могут выполниться с ошибкой. Если никак не обработать появление ошибки, то выполнение программы прекратится. Однако с помощью операторов **try** - **except** - **else** - **finally** можно повернуть работу программы в другое русло, и ее выполнение продолжится.
Совокупность данных операторов называется механизмом исключений.
Исключение, возникающее при работе программы, зависит от типа ошибки.

*Агоритм выполнения*.  Выполняется код, находящийся в теле под ключевым словом **try**. Возможно два варианта:
1.   Этот код не вызвал ошибку, тогда выполняется код в теле под ключевым словом **else**, затем выполняется код в теле под ключевым словом **finally**.
2.   Этот код вызвал ошибку, тогда выполняется проверка на соотвествие типа этой ошибки тому типу, который указан после ключевого слова **except**. Если такое совпадение найдено, то выполянется код в теле под ключевым словом **except**. Затем выполняется код в теле под ключевым словом **finally**.

Список всех встроеных исключений: https://docs.python.org/3/library/exceptions.html


В качестве упражнения, попробуйте поизменять значения ключа *value* в коде:

In [ ]:
my_dict = {"a": 1, "b": 2, "c": 3}

try:
    value = my_dict["z"]
except IndexError:  # Исключение, возникающее в случае обращения к несуществующему индексу
    print("This index does not exist!")
except KeyError:  # Обращение к несуществующему ключу словаря
    print("A KeyError occurred!")
else:
    print("No error occurred!")
finally:
    print("The finally statement ran!")

In [ ]:
try:
    a = 1 / 0
except ZeroDivisionError as e:  # Деление на ноль - это тоже исключение
    print('Get error:')
    print(e)

## Сортировка
Подробную информацию о сортировках можно получить тут: http://python-3.ru/page/sorted

Сортировка простого списка

In [ ]:
a = [3, 2, 5,  4, 7, 1]
a = sorted(a)  # Список отсортируется от наименьшего элемента к наибольшему
print(a)

Сортируем кортеж.

In [ ]:
t = ('Zane', 'Bob', 'Janet')
t = sorted(t)
print(t)  # ['Bob', 'Janet', 'Zane']

Сортировка словаря.

In [ ]:
d = {1:'a', 3:'c', 2:'b'}
d = sorted(d)
print(d)

Cортировка в обратном порядке производится, если указан параметр `reverse = True`:

In [ ]:
data = [3, 2, 5 ,4, 7, 1]
a = sorted(data, reverse=True)
print('a =', a)

data = ('Zane', 'Bob', 'Janet')
b = sorted(data, reverse=True)
print('b =', b)

Задать правила сортировки

In [ ]:
sortList = ['a', 'cc', 'bbb']
# Функция, для сортировки список в алфавитном порядке:
def sortByAlphabet(inputStr):
    return inputStr[0]  # Ключом является первый символ в каждой строке

print('Исходный список: ', sortList)

sortList.sort(key=sortByAlphabet)

print('Сортированный список: ', sortList)

## Функции
*Функция* - фрагмент программного кода, к которому можно обратиться из другого места программы.
Суть функции в том, чтобы получать на вход какие-то аргументы (возможно пустое множество аргументов),
выполнить какие-то действия и передать с помощью **return** результат своей работы обратно программе.

In [ ]:
def func(positional, keyword=value, *args, **kwargs):
    pass

+ **positional** - Позиционные аргументы. Необязательны, не имеют значений по умолчанию
+ **keyword** - Аргументы с ключевым словом. Необязательны, имеют значение по умолчанию
+ **args** - Список с произвольным количеством аргументов. Необязателен, не имеет значений по умолчанию
+ **kwargs** - Словарь с произвольным количеством аргументов. Необязателен, не имеет значений по умолчанию

Оператор `return` возвращает в то место, откуда вызывается функция, значение, которое идет следом за `return`:

In [ ]:
def add(a, b):
    return a + b

print(add(1, 2))

Присвоение значения по умолчанию:

In [ ]:
def add(a, b=1):
    return a + b

print('Передаем значение только a. Получаем: add(1) =', add(1))
print('Передаем значение a и b. Получаем: add(1, 10) =',add(1, 10))

Аргументы, находящиеся  после аргумента со значением по умолчанию, также должны иметь значение по умолчанию. Следующий пример вызовет **SyntaxError** ошибку:

In [ ]:
def fun(a, b = 2, c):  # SyntaxError: non-default argument follows default argument
    return a*b*c

Значения аргументов по умолчанию связываются с теми объектами, которые использовались в качестве значений аргументов во время объявления функции.

In [ ]:
a = 10
def foo(x=a):
    return(x)
print('a = {}, foo() = {}'.format(a, foo()))
a = 5
print('Изменили a = {}, значение foo() = {} не изменилось'.format(a, foo()))

Использование изменяемых (*mutable*) переменных в качестве значений по умолчанию может привести к неожиданным результатам.

In [ ]:
def foo(x, item=[]):
    item.append(x)
    return item
print(foo(1))
print(foo(2))
print(foo(3))

print('В примере при втором и последующих запусках функции foo() не использовалось значение по умолчанию, а использовалось последнее сохраненное в памяти значнеие')

Передача переменного числа аргументов:

In [ ]:
def foo(s, *args):
    print(s % args)

foo('%s %d', 'Hello', 42)

Переменные, объявленные в теле функции, называются *локальными* и доступны только в этой функции. Переменные объявленные в теле основной программы являются *глобальными* при выполнении функции.

Без предварительного объявления *глобальных* переменных в функции можно использовать их значения, однако эти значения нельзя изменить.
Для изменения значения *глобальных* переменных их необходимо объявить в функции,используя ключевое слово `global`.
Пример использования *глобальных* переменных:

In [ ]:
a = 1
b = 2
c = 67
def fun():
    global a
    a = 3
    b = 5  # Создалась локальная переменная b
    print(c)  # Для операции вывода, когда не находится значение переменной среди локальных,
              # продолжается поиск среди глобальных переменных
fun()
print(a, b)
print(b)

Попытка использовать в функции глобальную переменную без её объявления выховет `UnboundLocalError` ошибку:

In [ ]:
a = 1
def fun():
    #global a
    a += 1  # UnboundLocalError: local variable 'a' referenced before assignment
fun()

В качестве упражнения следует разобраться в коде и выводимой информации:

In [ ]:
def f1(a):
    a += 1
    def f2(a):
        a += 1
        print('f2', a)
    f2(a)
    print('f1', a)
f1(0)

Пример передачи функции в качестве параметра:

In [ ]:
def call(func):
    return func()

def hw():
    return "Hello world!"

call(hw)

Добавление атрибута к функции:

In [ ]:
def foo():
    pass

foo.secure = 1  # secure - атрибут
print(foo.secure)

## Lambda функции

Labmda функции - анонимные функции.
Это простые однострочные функции, объявляемые через lambda.

In [ ]:
def f(x):
    return x*2
f(2)

In [ ]:
f = lambda x: x * 2
f(2)

In [ ]:
(lambda x: x * 2)(2)

## Декоратор @

обертка для других функций или класса.
Основная задача декораторов - избежать повторения одного и того же кода. Рассмотрим пример:

In [ ]:
# Объявление декоратора:
def makebold(fn):
    def wrapped():
        return '<b>' + fn() + '</b>'
    return wrapped

# Объявление декоратора:
def makeitalic(fn):
    def wrapped():
        return "<i>" + fn() + "</i>"
    return wrapped

# Применение двух декораторов к результатам функции hello():
@makebold
@makeitalic
def hello():
    return 'hello world'

hello()

## Рекурсия

Рассмотрим на примере, в котором расчитывается факториал переданного числа.

In [ ]:
def factor(n):
    if n <= 1:
        return 1
    else:
        return n * factor(n-1)

factor(3)

Узнать предел рекурсии можно с помощью функции getrecursionlimit() из модуля sys

In [ ]:
import sys
sys.getrecursionlimit()

## eval, exec, compile

### eval(str)

Выполняет действие в строке:

In [ ]:
eval('3 * 9 + 4')  # 31

Все эти три функции следует использовать с крайней осторожностью, так как они открывают огромное пространство для возможных уязвимостей, связанных с выполнением произвольного кода.

In [ ]:
eval('3 * 9 ,(lambda x: list(__import__("os").listdir(__import__("os").path.curdir)))(1)')  # Список файлов в текущей директории

### exec(str)

Выполняет код в строке:

In [ ]:
a = [1,2,3]
exec('for i in a: print(i)')

### compile(str, filename, kind)

Компилирует сроку `str` в байт-код. `filename` – файл, в котором эта строка определена, (если файла нет, то можно указать `' '`). `kind` определяет тип компилируемого кода:

*   ‘single’ – для одной конструкции,
*   ‘exec’ – для множества конструкций,
*   ‘eval’ – выражение.

In [ ]:
s = 'for i in range(5): print(i)'
c = compile(s, '', 'exec')
exec(c)

## Help, получение справки

Получение справки по функции:

In [ ]:
help(max)

In [ ]:
max.__doc__

Можно написать справку для своих функций, которя так же будет доступна через применение .\_\_doc\_\_ (с помощью docstring).

In [ ]:
def foo(x):
    ''' Функция для возведения x в степень '''
    return x * x
foo.__doc__

В ipython и в Jupyter Notebook _(да, да, прямо здесь)_ можно поставить знак вопрос после объекта для получения справки.

In [ ]:
?max

## Функции стандартной библиотеки. Build-in Functions

Функции в стандартной библиотеке, которые не нужно импортировать.

Полный их список, например, для Python3.8:
https://docs.python.org/3.8/library/functions.html

| \_|\_|\_|\_|        Built-in Functions      |
| --- | --- | --- | --- | --- |
| abs() | dict() | help() | min() | setattr() |
| all() | dir() | hex() | next() | slice() |
| any() | divmod() | id() | object() | sorted() |
| ascii() | enumerate() | input() | oct() | staticmethod() |
| bin() | eval() | int() | open() | str() |
| bool() | exec() | isinstance() | ord() | sum() |
|breakpoint()|
| bytearray() | filter() | issubclass() | pow() | super() |
| bytes() | float() | iter() | print() | tuple() |
| callable() | format() | len() | property() | type() |
| chr() | frozenset() | list() | range() | vars() |
| classmethod() | getattr() | locals() | repr() | zip() |
| compile() | globals() | map() | reversed() | \_\_import\_\_() |
| complex() | hasattr() | max() | round() | \_ |
| delattr() | hash() | memoryview() | set() | \_ |

## type, isinstance

С помощью `type()` можно получить тип объекта или проверить, принадлежит ли объект какому-то типу:

In [ ]:
a = 10
print(type(a))
print(type(a) == int)

То же самое можно сделать с помощью функции isinstance().

In [ ]:
a = 10
isinstance(a,int)

Но isinstance так же поддерживает наследование и может проверить принадлежность хоть одному классу из списка.
Подробнее о наследовании будет сказано в следующих блокнотах.

In [ ]:
class A(list):
    pass
a = A()
print(type(a) == list)
print(isinstance(a, list))

## assert

Проверяет выполнение условия. Если не выполняется, то возбуждается AssertionError.

In [ ]:
assert False

Класс **TestCase** из модуля **unittest** представляет некоторое количество методов для тестирования и сообщения об ошибках:

| Метод | Проверяет что | Начиная с |
| --- | --- | --- |
| assertEqual(a, b) | a == b | \_ |
| assertNotEqual(a, b) | a != b | \_ |
| assertTrue(x) | bool(x) is True | \_ |
| assertFalse(x) | bool(x) is False | \_ |
| assertIs(a, b) | a is b | 2.7 |
| assertIsNot(a, b) | a is not b | 2.7 |
| assertIsNone(x) | x is None | 2.7 |
| assertIsNotNone(x) | x is not None | 2.7 |
| assertIn(a, b) | a in b | 2.7 |
| assertNotIn(a, b) | a not in b | 2.7 |
| assertIsInstance(a, b) | isinstance(a, b) | 2.7 |
| assertNotIsInstance(a, b) | not isinstance(a, b) | 2.7 |

In [ ]:
import unittest
test = unittest.TestCase()
a = .01
b = .11 - .1
print('a =', a)
print('b =', b)

test.assertAlmostEqual(a, b)  # Проверка на _почти_ равенство, проходит
print('Проверка на полное равенство, не проходит (т.к. возникает погрешность вычисления. Для решения этой проблемы можно использовать модуль decimal')
test.assertEqual(a, b)

##Ответы на задачи:

<a name="exercise_1"></a>
## Ответ на задачу 1

In [ ]:
import math
print(math.pow(5,4))

<a name="exercise_2"></a>
## Ответ на задачу 2

In [ ]:
print(mathlib.pow(5,4))

<a name="exercise_3"></a>
## Ответ на задачу 3

In [ ]:
d = 5
d -= 7
d *= 10
print(d)

<a name="exercise_8"></a>
## Ответ на задачу 4

In [ ]:
b = 5
if b < 0:
    print("b - отрицательное число!")
elif b == 0:
    print("b равно нулю!")
elif b < 3:
    print("b меньше трех!")
else:
    print("b больше или равно трем!")

<a name="exercise_10"></a>
## Ответ на задачу 5

In [ ]:
a = 0
while a < 5:
    a += 1
    print(a)
    if a == 2:  # Пропустить ход если а == 2
        continue
    if a == 4:  # Выйти из цикла если a == 4
        continue  # Изменения тут
    print('continue ', a)
else:
    print('all out')  # Строка не выполнится, так как при a=4, выполнится break и else будет пропущен

<a name="exercise_9"></a>
## Ответ на задачу 6

In [ ]:
for i in range(100,0,-10):
    print(i)

<a name="exercise_11"></a>
## Ответ на задачу 7

In [ ]:
i = 100
while i > -1:
  if i%10 == 0:
    print(i)
  i -= 1

<a name="exercise_4"></a>
## Ответ на задачу 8

In [ ]:
a = "What a wonderful world?"
print(a[7:16])

<a name="exercise_5"></a>
## Ответ на задачу 9

In [ ]:
first_name = 'Vasya'
second_name = 'Ivanov'
cat_name = 'Barsik'
print('%s %s has a cat %s' % (second_name, first_name, cat_name))

<a name="exercise_6"></a>
## Ответ на задачу 10

In [ ]:
animals = ["cat", "dog", "horse"]
print(animals[1])

<a name="exercise_7"></a>
## Ответ на задачу 11

In [ ]:
list_a = [1,2,3]
list_b = list_a.copy()
list_b[2] = 4
print(list_a)
print(list_b)

<a name="exercise_12"></a>
## Ответ на задачу 12

In [ ]:
a = {2, 1, 3, 4}
b = {1, 2, 3, 5}
a.intersection_update(b)
b.intersection_update(a)
print(a.intersection(b))
print(a)
print(b)